package com.silo.common.logging.enums;

public enum AuditResource {
    MEMBER,
    CONTRIBUTION,
    LOAN_REQUEST,
    LOAN,
    LOAN_INSTALLMENT,
    LOAN_GUARANTOR,
    GUARANTOR_LIABILITY,
    REPAYMENT,
    LEDGER_ACCOUNT,
    LEDGER_ENTRY,
    PAYSTACK_TRANSACTION,
    NOTIFICATION_LOG,
    REPORT,
    BORROWER_RISK_PROFILE,
    GUARANTOR_CREDIBILITY_PROFILE,
    REPORTING_MEMBER_SUMMARY,
    REPORTING_LOAN_SUMMARY
}
