spring.application.name=Silo

silo.jwt.secret=${SILO_JWT_SECRET:BJw7jNTC9RvjU4N7z6xJP8SmtMdtJxNrZyWPGBnNDihYOszPaehI9194e4l}
silo.jwt.expiration-minutes=${SILO_JWT_EXPIRATION_MINUTES:15}
silo.jwt.refresh-expiration-days=${SILO_JWT_REFRESH_EXPIRATION_DAYS:7}
